theme: slate
title: [Full-stack Markdown Book]
description: [Compilation of Odin Project Curriculum]
show_downloads: ["true"]
# google_analytics: [Your Google Analytics tracking ID]
markdown: kramdown
baseurl: ""
url: "https://cliffordwilliam.github.io" # Your GitHub Pages URL